// IHM_COULEURS.INC
// Codes couleurs standard 4DGL (RGB565)

#constant BLACK 0x0000
#constant NAVY 0x000F
#constant DGREEN 0x03E0
#constant DCYAN 0x03EF
#constant MAROON 0x7800
#constant PURPLE 0x780F
#constant OLIVE 0x7BE0
#constant GREY 0x8410
#constant BLUE 0x001F
#constant GREEN 0x07E0
#constant CYAN 0x07FF
#constant RED 0xF800
#constant MAGENTA 0xF81F
#constant YELLOW 0xFFE0
#constant WHITE 0xFFFF
#constant ORANGE 0xFD20
#constant GREENYELLOW 0xAFE5
#constant PINK 0xF81F
