// IHM_ECRANS.INC
// Liste des ecrans du projet

#constant ECRAN_ACCUEIL 0
#constant ECRAN_MENU 1
#constant ECRAN_ECLAIRAGE 2
#constant ECRAN_VOLETS 3
#constant ECRAN_CHAUFFAGE 4
#constant ECRAN_SCENARIOS 5
#constant ECRAN_CONSO 6
#constant ECRAN_SETTINGS 7
#constant ECRAN_VEILLE 8
#constant ECRAN_SCENARIOS_1 9
#constant ECRAN_SCENARIOS_2 10
#constant ECRAN_JE_SORS 11
#constant ECRAN_JE_SUIS_SORTI 12
#constant ECRAN_JE_VAIS_ME_COUCHER_DEBUT 13
